name: Deploy Resume to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # required to push to gh-pages

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        submodules: 'true'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Export HTML Resume
        run: |
            npm install
            cp -r jsonresume-theme-juned node_modules/jsonresume-theme-juned
            node_modules/resumed/bin/resumed.js --theme jsonresume-theme-juned -o target/index.html
            node_modules/resumed/bin/resumed.js export -o target/juned_resume.pdf -t jsonresume-theme-juned

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
          destination_dir: .
          publish_branch: gh-pages
          user_name: github-actions
          user_email: github-actions@github.com
          keep_files: false
